[window]
decorations = "None"
opacity = 1.0
blur = false
option_as_alt = "Both"
# startup_mode = "SimpleFullscreen" 

[cursor]
style = { shape = "Block", blinking = "Off" }
thickness = 0.2
blink_interval = 100
blink_timeout = 1

[mouse]
hide_when_typing = true

[general]

# shell = { program = "~/bin/zsh", args = [] }

live_config_reload = true
import = [
	"~/.dotfiles/.config/alacritty/themes/themes/campbell.toml",
	# "~/.dotfiles/.config/alacritty/themes/themes/alabaster.toml",

	# "~/.dotfiles/.config/alacritty/fonts/Fantasque.toml"
	"~/.dotfiles/.config/alacritty/fonts/MonoLisa.toml"
]
